### ISSUE TITLE
implements login

### ISSUE THREAD

**Issue by AntoineDrouhin** [AntoineDrouhin/expenses-tracker#25]
CRUD User
Encode Password (sha ...) on server side

**Comment by devenvag** [comment]
Regarding more general authentication best practices about hashing, password policy and transport over http(s) :

[BEST PRACTICES WEB APP AUTHENTICATION](https://codingkilledthecat.wordpress.com/2012/09/04/some-best-practices-for-web-app-authentication/)

**Comment by devenvag** [comment]
More specific about the /Login api entry point : Password, token, id or anything else that are private and critical from a user should not appear in the url (GET) but in the body part (POST).

From OWASP best practices : 
[OWASP BEST PRACTICES SESSION MANAGEMENT](https://www.owasp.org/index.php/REST_Security_Cheat_Sheet#Session_management)

**Comment by devenvag** [comment]
And the last critical configuration for the cookie:
[COOKIE SECURE FLAG HTTPS CONFIGURATION](https://www.owasp.org/index.php/SecureFlag)

Prevent XSS sessionid or anything else that are originally readable in the cookie key/val.

**Comment by AntoineDrouhin** [comment]
disconnect user ?
